### ISSUE TITLE
Flask api 서버에서 동작 확인하기

### ISSUE THREAD

**Issue by eubinecto** [eubinecto/youtora#76]
#20 이 이슈에 이어서, 이제는 eubinCloud에서 api를 호스팅하는 설정을 해보도록 하자.

## 왜?
계속 바꾸어 나가야 하기는 하지만, 일단 종윤이가 일을 시작할 수 있도록 api를 구현해 놓는 것이 급 선무. 

## 무엇을?
- 플라스크 포트가 몇번이더라? 포트 알아내고 포트 포워딩 하기.  ufw로 포트 여는 것도 잊지말기
- 플라스크 서버 열어두기
- 아 그런데.. public IP를 외부로 노출하는 건 좀 그렇다. 이걸 hostname으로 감추는 방법은 없나?

## 어떻게?
- 공유기 설정에서 포트포워딩
- ufw 로 포트 열기 

플라스크 서버 열어두는 방법?
1. flask run 할 때, 실행할 플라스크 스크립트를 환경변수에서 설정
2. 아마도 systemctl start flask 일 것 같은데?

**Comment by eubinecto** [comment]
## public IP 감추는 방법?

**Comment by eubinecto** [comment]
## 플라스크 포트?

**Comment by eubinecto** [comment]
## api개발은 그러면 어떻게?
개발은 내 맥에서 하게될 것이니.. api를 변경할 일이 있으면, 로컬에서 호스팅을 해서 하자. 로컬에서 flask run을 한 다음 그 entrypoint를 가지고 테스팅을 하는 방식으로 진행하기.

**Comment by eubinecto** [comment]
## systemctl 활용해서 api 서비스 하기

systemctl을 활용하기 위해서는, 내가 직접 서비스를 할 스크립트를 systemd로 지정해야하는 것 같다.
- https://blog.miguelgrinberg.com/post/running-a-flask-application-as-a-service-with-systemd

음.. 이렇게 하는 편이 컴퓨터를 켜서 플라스크를 위한 터미널을 띄워놓는 것보다 더 나은 방법일 듯.

터미널을 따로 띄워놓으면 터미널이 종료될경우, 로그가 다 날라감. 하지만 systemctl로 활성화를 해놓으면, 활성화된 모든 서비스의 로그들을
journalctl로 확인할 수 있다.

예시)
```
root@eubinCloud:/home/eubin# journalctl -u elasticsearch.service
-- Logs begin at Thu 2020-05-07 22:12:23 KST, end at Wed 2020-09-02 10:50:02 KST. --
 9월 01 15:02:13 eubinCloud systemd[1]: Starting Elasticsearch...
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]: uncaught exception in thread [main]
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]: java.lang.IllegalStateException: Unable to access 'path.data' (/media/database/lib/elasticsea>
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]: Likely root cause: java.nio.file.AccessDeniedException: /media/database
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at java.base/sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider>
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at java.base/java.nio.file.Files.createDirectory(Files.java:694)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at java.base/java.nio.file.Files.createAndCheckIsDirectory(Files.java:801)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at java.base/java.nio.file.Files.createDirectories(Files.java:787)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.bootstrap.Security.ensureDirectoryExists(Security.java:389)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.bootstrap.FilePermissionUtils.addDirectoryPath(FilePermissionUti>
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.bootstrap.Security.addFilePermissions(Security.java:297)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.bootstrap.Security.createPermissions(Security.java:252)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.bootstrap.Security.configure(Security.java:121)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:222)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java>
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.cli.Command.main(Command.java:90)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]:         at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
 9월 01 15:02:16 eubinCloud systemd-entrypoint[8932]: For complete error details, refer to the log at /var/log/elasticsearch/elasticsearch.log
 9월 01 15:02:16 eubinCloud systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
 9월 01 15:02:16 eubinCloud systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
 9월 01 15:02:16 eubinCloud systemd[1]: Failed to start Elasticsearch.
 9월 01 15:03:47 eubinCloud systemd[1]: Starting Elasticsearch...
 9월 01 15:03:50 eubinCloud systemd-entrypoint[9158]: uncaught exception in thread [main]
 9월 01 15:03:50 eubinCloud systemd-entrypoint[9158]: java.lang.IllegalStateException: Unable to access 'path.data' (/media/database/lib/elasticsea>
 9월 01 15:03:50 eubinCloud systemd-entrypoint[9158]: Likely root cause: java.nio.file.AccessDeniedException: /media/database
 9월 01 15:03:50 eubinCloud systemd-entrypoint[9158]:         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)

```

앗 .. 이걸 어제 진작에 보았다면 AccessDeniedException이라는 것을 바로 알 수 있었을텐데! 아무튼 이렇게 유용하다.

때문에, 왠만해서는 systemctl를 활용을 해서 api를 호스팅하는 편이 가장 나을 것!

**Comment by eubinecto** [comment]
## 커스텀 서비스 설정하는 법
위에도 링크가 있지만, 다시 링크:
- https://blog.miguelgrinberg.com/post/running-a-flask-application-as-a-service-with-systemd

먼저, /etc/systemd/system/  경로에, .serivce 로 끝나는 설정파일을 셋업 해야함.

다음과 같이 설정해보았음:
```
[Unit]
Description=api service for youtora
After=network.target

[Service]
User=ubuntu
Environment=FLASK_APP=/home/eubin/youtora/api/views.py
WorkingDirectory=/home/eubin/youtora
ExecStart=flask run -host:0.0.0.0
Restart=always

[Install]
WantedBy=multi-user.target
```

하지만 역시나, 실행을 해보니 오류가 뜬다:
```
eubin@eubinCloud:~/youtora$ sudo systemctl start youtopia
Failed to start youtopia.service: Unit youtopia.service has a bad unit file setting.
See system logs and 'systemctl status youtopia.service' for details.
eubin@eubinCloud:~/youtora$ systemctl status youtopia.service 
● youtopia.service - api service for youtora
     Loaded: bad-setting (Reason: Unit youtopia.service has a bad unit file setting.)
     Active: inactive (dead)

 9월 02 18:13:47 eubinCloud systemd[1]: /etc/systemd/system/youtopia.service:8: Executable "flask" not found in path "/usr/local/sb>
 9월 02 18:13:47 eubinCloud systemd[1]: youtopia.service: Unit configuration has fatal error, unit will not be started.
 9월 02 18:13:58 eubinCloud systemd[1]: /etc/systemd/system/youtopia.service:8: Executable "flask" not found in path "/usr/local/sb>
 9월 02 18:13:58 eubinCloud systemd[1]: youtopia.service: Unit configuration has fatal error, unit will not be started.
 9월 02 18:14:15 eubinCloud systemd[1]: /etc/systemd/system/youtopia.service:8: Executable "flask" not found in path "/usr/local/sb>
 9월 02 18:14:15 eubinCloud systemd[1]: youtopia.service: Unit configuration has fatal error, unit will not be started.
 9월 02 18:19:17 eubinCloud systemd[1]: /etc/systemd/system/youtopia.service:9: Executable "flask" not found in path "/usr/local/sb>
 9월 02 18:19:17 eubinCloud systemd[1]: youtopia.service: Unit configuration has fatal error, unit will not be started.
 9월 02 18:19:24 eubinCloud systemd[1]: /etc/systemd/system/youtopia.service:9: Executable "flask" not found in path "/usr/local/sb>
 9월 02 18:19:24 eubinCloud systemd[1]: youtopia.service: Unit configuration has fatal error, unit will not be started.
```

**Comment by eubinecto** [comment]
## 이제 api 호스팅은 만사 오케이
- 서비스 설정 파일 수정시: `systemctl daemon-reload`
- api 호스팅 시작: `systemctl start youtopia`
- api 호스팅 로그 보기: `journalctl -u youtopia`
